### ISSUE TITLE
Path issue in NetBSD

### ISSUE THREAD

**Issue by martintc** [kraileth/miniraven#1]
Running it on NetBSD, there is an issue where it will not grab tools brought in by raven even when specified first in the path variable. Bootstrapping Raven (did not get cmake to build) via miniraven generates the /raven directory with applications in /raven/bin. Testing this, I did

```sh
export PATH=/raven/bin:$PATH
```

Then running
```sh
whereis cat
```

Yielded
```
/bin/cat
```

**Comment by kraileth** [comment]
It is a bit weird, but that is in fact the expected behavior. Interesting to see though that NetBSD's whereis and FreeBSD's differ in what they do. Traditonally, `whereis(1)` is a command that searches for binaries in the paths defined in the sysctl `user.cs_path` - and that's exactly what it still does on NetBSD. On FreeBSD, the PATH environment variable gets appended to what `user.cs_path` contains.

You can either try

```
which cat
```

and that should result in

```
/raven/bin/cat
```

if you exported the PATH like you did before as `which` searches in the directories listed in the PATH environment variable.

Another option is supplying `whereis` with a flag to use PATH instead of the sysctl:

```
whereis -p cat
```

which outputs

```
/raven/bin/cat
/bin/cat
```
