### ISSUE TITLE
Cmake issue on NetBSD

### ISSUE THREAD

**Issue by martintc** [kraileth/miniraven#2]
Already known about, but placing a github issue to track this.

Output from failure:
```sh
localhost# python3.9 miniraven.py -p
Config: Configuration is valid.
System: Set for x86_64-raven-netbsd9.
Programs: All required external programs are available.
Filesystem: Hierarchy is in place.

Information summary:
--------------------------------------
OSNAME: NetBSD
OSVERSION: 900200
OSRELEASE: 9.2
OSMAJOR: 9
OSARCH: x86_64
STDARCH: x86_64
TARGET_TRIPLE: x86_64-raven-netbsd9
--------------------------------------

24 packages present:
patch bmake uname bzip2 xz perl coreutils ncurses sed m4 autoconf automake libtool pkgconf gmake zstd expat libarchive libressl libb2 picosat linenoise libucl uthash
3 packages missing:
cmake elftoolchain ravensw

Build missing packages now? (Y/N) Y

Old workdir found. Deleting... ok
Extracting "cmake-3.21.1.tar"... ok

Error: Shell execution failed!
stdout: can't find file to patch at input line 3
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|--- Utilities/cmlibuv/src/unix/core.c.orig     2021-07-14 14:10:23 UTC
|+++ Utilities/cmlibuv/src/unix/core.c
--------------------------
File to patch:
Skip this patch? [y]
Skipping patch.
1 out of 1 hunk ignored
```

With my env as follows:
```sh
localhost# env
ENV=/root/.shrc
BLOCKSIZE=1k
PWD=/usr/miniraven
HOME=/root
PATH=/raven/bin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/pkg/sbin:/usr/pkg/bin:/usr/X11R7/bin:/usr/local/sbin:/usr/local/bin
HOST=localhost
TERM=xterm-256color
OLDPWD=/raven
USER=root
LOGNAME=root
SU_FROM=todd
SHELL=/bin/sh
```

Interestingly, it fails differently depending on the PATH. As shown above, I have /raven/bin in my path and it failed at extracting the tar for CMake. When that is not in PATH, it fails during compilation with issues of not being able to use __gnu_cxx::vsscanf and other similar function declarations.

**Comment by kraileth** [comment]
Thanks for reporting this! What happens here is that we have a version of patch in the base system on NetBSD and GNU patch build for raven. The two are not compatible and obviously trying to apply the cmake patches using GNU patch leads to the error output above.

I added GNU patch because not all platforms may have `patch` available on a basic install (e.g. most Linux distros). If that one is not capable of applying the needed patches, that's pretty sad. Another good reason to try and get rid of cmake for the bootstrap process. Elftoolchain (which currently needs cmake to build as Ravenports does it) comes with regular Makefiles, too. I'll take a look at building it that way and ditching cmake completely.

**Comment by kraileth** [comment]
Ok, it's not just unnecessary to build the whole of `elftoolchain` - in fact only a single file from it seems to be needed to satisfy the requirements for the ravensw package manager: **libelf_pic.a**. It certainly _is_ overkill to first build cmake to then build the complete elftoolchain suite via the custom cmake list files. If I can find out how to properly build that one static library, cmake as well as unneeded patches and cmake files for elftoolchain can all be dropped! That would make the bootstrap much, much more straight-forward and quicker to do. And who likes to waste time compiling?

There's most likely more such packages where building a reduced set of files would suffice. Might be something to look into somewhen in the future. But since cmake is de facto a pain point in multiple regards right now, I'd really prefer to ditch it.

**Comment by martintc** [comment]
I'd also like to ditch it is possible. NetBSD make files are pretty straight forward and we could potentially use some nice tools in pkgsrc to maybe generate one, something close, or something easier to translate from. 

Looking at the github repo for elftoolchain, it is already designed to be made with bmake. 
https://github.com/elftoolchain/elftoolchain/blob/trunk/GNUmakefile
Wonder if we can leverage this to cut out Cmake? Perhaps ditch the custom cmake and just pull in bmake and use the default bmake script already provided by elftoolchain? It doesn't escape building the whole package, but it would simplify things by not needing to write a new script, atleast in the short term. Perhaps using this we can possibly leverage pkgsrc to pick up some slack? Essentially supplement ravensw with pkgsrc as needed until a native port to ravensw can be written. We will perhaps need to make some changes to some of raven so that we don't have pkgsrc building dependencies that already exist because raven built them, but we may be able to find a work around so they work together.

**Comment by kraileth** [comment]
It might be even easier, requiring almost no additional work. Since there's already Makefiles for the project there, we can probably just use the one for the single part of the project we care about and then manually create the PIC library as done for libarchive already.

Just tried that by hand outside of miniraven. The result is a libelf_pic.a that's a pretty heavy-weight 1.2 MB in size instead of the 333k of the one produced by cmake. `ar -t` shows the same count of files (58) in both archives, though. Will take a closer look at both, comparing some of the symbols contained in them to maybe see what I did wrong. If this can be sorted out, cmake's done for.

**Comment by martintc** [comment]
Just saw some of the latest commits, when I get home from work I will definitely be pulling this down and testing it out on my test machine.

**Comment by martintc** [comment]
So far the issue I have it on NetBSD is

```sh
*** Error code 1

Stop.
make: stopped in /var/ravenbuild/construction/elftoolchain-0.7.1/libelf

stderr: libelf_ar.c: In function ‘_libelf_ar_process_bsd_symtab’:
libelf_ar.c:330:13: error: conversion to ‘unsigned int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
  nentries = (size_t) arraysize / entrysize;
             ^
cc1: all warnings being treated as errors
```

**Comment by kraileth** [comment]
Thanks for reporting! Put the NetBSD drive back into my test machine and took a look. Thing here is that while the elftoolchain project is maintained and still worked on, they haven't made a new official release in the past 5 years. Since compilers have become more and more picky (and usually rightfully so), we've got to ignore this kind of warning in our case. After telling GCC to relax a bit, the required library builds successfully on NetBSD for me.

Unless for some reason it still doesn't work for you, we can probably close this issue. Ravensw still fails to build, but that is now the same error across all platforms. So NetBSD support has basically caught up with the other two. (Will write you a mail about the other problem and about getting into Raven in general.)
